"""Web service: the public dashboard, plus the Databricks sign in flow.

The workspace issues OAuth app integrations rather than service principal
secrets, so this app cannot authenticate as itself. It authenticates as
whoever signs in, using the authorization code flow, and the token it gets
back carries that person's own permissions.

The consequence is worth stating plainly rather than discovering later: only
someone with an account in this Databricks workspace can use anything behind
the sign in. Pages meant for a manufacturer or a journalist have to be served
from published data instead, which is what `/` does. The data file is built by
`scripts/export_public_data.py` from the gold tables, so the page needs no
warehouse, no token and no round trip to REE.

Routes:
    /           the dashboard, served from app/public/index.html
    /data.json  the published gold data the dashboard reads
    /signin     name yourself, which is what the workbench means by a session
    /workbench  the analyst's tool, behind that name
    /auth       sign in status, and a link to start the flow
    /login      redirect to Databricks
    /callback   exchange the code for a token and report what came back
    /healthz    liveness, no auth

`/signin` and the Databricks flow are two different things and the names get
confused, so: the Databricks flow proves an identity and is what anything
touching the workspace on a person's behalf would need. `/signin` proves
nothing. It attributes rows to a name so two reviewers' judgements stay apart,
and the page says so in as many words. The workbench is deliberately behind the
second and not the first, because it has to be usable by somebody reviewing this
project who has no account in this workspace.

Configuration, all from the environment:
    DATABRICKS_HOST           https://dbc-xxxxxxxx-xxxx.cloud.databricks.com
    APP_OAUTH_CLIENT_ID       from the app integration
    APP_OAUTH_CLIENT_SECRET   from the app integration
    DATABRICKS_REDIRECT_URI   must match a registered redirect URL exactly
    DATABRICKS_SCOPES         space separated, defaults to "all-apis"

The two credentials are deliberately NOT called DATABRICKS_CLIENT_ID and
DATABRICKS_CLIENT_SECRET. The Databricks SDK and CLI treat those names as a
service principal to authenticate with, so any shell that has them set has the
CLI trying to log in as this web app. That cost an afternoon of invalid_client
once already, and the fix is to keep the app's credentials out of the SDK's
namespace rather than to remember not to export them.
"""

from __future__ import annotations

import base64
import hashlib
import html
import json
import os
import secrets
import time
import urllib.parse
from pathlib import Path

import requests
from fastapi import Cookie, FastAPI, HTTPException, Query
from fastapi.responses import FileResponse, HTMLResponse, RedirectResponse

app = FastAPI(title="MIBEL Market Intelligence")

# The workbench: the half that reaches Lakebase and the agent. Imported inside a
# try so a deployment without those variables still serves the dashboard. That
# is not defensive programming for its own sake: the dashboard is what a visitor
# lands on, and it needs nothing to be awake.
try:
    import sys

    _SRC = Path(__file__).resolve().parents[1] / "src"
    if _SRC.is_dir() and str(_SRC) not in sys.path:
        sys.path.insert(0, str(_SRC))

    from app.api import router as workbench_router

    app.include_router(workbench_router)
    WORKBENCH = True
except Exception as exc:  # pragma: no cover - configuration, not logic
    print(f"workbench routes not loaded: {type(exc).__name__}: {exc}")
    WORKBENCH = False

#: Everything the dashboard needs, next to this module so the app deploys as
#: one directory. `data.json` is a build product and is regenerated by
#: scripts/export_public_data.py; `index.html` is source.
PUBLIC = Path(__file__).resolve().parent / "public"

HOST = (os.environ.get("DATABRICKS_HOST") or "").rstrip("/")
CLIENT_ID = os.environ.get("APP_OAUTH_CLIENT_ID", "")
CLIENT_SECRET = os.environ.get("APP_OAUTH_CLIENT_SECRET", "")
REDIRECT_URI = os.environ.get("DATABRICKS_REDIRECT_URI", "")
# all-apis rather than postgres. The callback calls the workspace API to
# generate a database credential, and a token scoped only to Postgres cannot
# make that call. The token this buys is broad, which is precisely why the
# callback spends it immediately and keeps only what it produced.
SCOPES = os.environ.get("DATABRICKS_SCOPES", "all-apis")

AUTHORIZE_URL = f"{HOST}/oidc/v1/authorize"
TOKEN_URL = f"{HOST}/oidc/v1/token"

# One pending sign in per state value. The flow is short lived and this app
# runs as a single instance, so a dict is enough. Anything longer lived would
# need a real session store, which is a problem for the day there is one.
_PENDING: dict[str, dict] = {}
_PENDING_TTL_SECONDS = 600
_PENDING_MAX = 50


def configured() -> list[str]:
    """Which required settings are missing, so the page can say so."""
    return [
        name
        for name, value in (
            ("DATABRICKS_HOST", HOST),
            ("APP_OAUTH_CLIENT_ID", CLIENT_ID),
            ("APP_OAUTH_CLIENT_SECRET", CLIENT_SECRET),
            ("DATABRICKS_REDIRECT_URI", REDIRECT_URI),
        )
        if not value
    ]


def _prune() -> None:
    cutoff = time.time() - _PENDING_TTL_SECONDS
    for state in [s for s, v in _PENDING.items() if v["created"] < cutoff]:
        _PENDING.pop(state, None)
    while len(_PENDING) > _PENDING_MAX:
        _PENDING.pop(next(iter(_PENDING)))


def _pkce() -> tuple[str, str]:
    """Verifier and S256 challenge.

    The workspace advertises S256 as its only challenge method, so send it
    even though a confidential client does not strictly need PKCE.
    """
    verifier = base64.urlsafe_b64encode(secrets.token_bytes(48)).decode().rstrip("=")
    digest = hashlib.sha256(verifier.encode("ascii")).digest()
    challenge = base64.urlsafe_b64encode(digest).decode().rstrip("=")
    return verifier, challenge


def decode_claims(token: str) -> dict:
    """Read a JWT payload without verifying the signature.

    Verification is the resource server's job. This is here so a human can see
    which identity the token belongs to and which scopes actually came back,
    which is often narrower than what was requested.
    """
    try:
        payload = token.split(".")[1]
    except IndexError:
        return {}
    padding = "=" * (-len(payload) % 4)
    try:
        return json.loads(base64.urlsafe_b64decode(payload + padding))
    except Exception:
        return {}


#: The cookie is allowed to outlive the credential it points at, on purpose. A
#: browser holding a cookie whose session has expired gets a clean redirect to
#: sign in; a browser with no cookie at all gets the same thing with no way to
#: say why. The first is a better page to land on.
SESSION_COOKIE_SECONDS = 8 * 3600

#: Which Lakebase endpoint the credential is generated for. Same shape as the
#: notebooks use, and read from the environment for the same reason.
def lakebase_endpoint() -> str:
    """Which Lakebase endpoint a credential is generated for.

    No defaults. A fallback here would be one person's project name compiled
    into a public repository, and worse, a misconfigured deployment would point
    at it and fail somewhere confusing instead of at start up with a name.
    """
    missing = [
        name
        for name in ("LAKEBASE_PROJECT", "LAKEBASE_BRANCH", "LAKEBASE_ENDPOINT_ID")
        if not os.environ.get(name)
    ]
    if missing:
        raise RuntimeError(
            f"Not configured: {', '.join(missing)}. The workbench cannot "
            "generate a database credential without knowing which endpoint."
        )
    return (
        f"projects/{os.environ['LAKEBASE_PROJECT']}"
        f"/branches/{os.environ['LAKEBASE_BRANCH']}"
        f"/endpoints/{os.environ['LAKEBASE_ENDPOINT_ID']}"
    )


def database_credential_for(access_token: str) -> str:
    """Spend a person's platform token on one Lakebase credential.

    The SDK client is built around the token rather than the environment, so
    this call is made as the person who signed in and not as whatever identity
    the process happens to be configured with. That is the whole point: the
    database sees the reviewer, and their own grants decide what they can do.

    Imported here rather than at module scope so the dashboard half of this
    service still starts on a host without the SDK installed.
    """
    from databricks.sdk import WorkspaceClient

    workspace = WorkspaceClient(host=HOST, token=access_token, auth_type="pat")
    return workspace.postgres.generate_database_credential(
        endpoint=lakebase_endpoint()
    ).token


def page(title: str, body: str) -> HTMLResponse:
    return HTMLResponse(
        f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{html.escape(title)}</title>
<style>
  :root {{ color-scheme: light dark; }}
  body {{ font: 16px/1.6 ui-sans-serif, system-ui, sans-serif;
         max-width: 44rem; margin: 3rem auto; padding: 0 1rem; }}
  code, pre {{ font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
              font-size: 0.9em; }}
  pre {{ padding: 1rem; overflow-x: auto; border-radius: 6px;
        background: rgba(127,127,127,0.12); }}
  .ok {{ color: #16794a; }} .bad {{ color: #b3261e; }}
  @media (prefers-color-scheme: dark) {{ .ok {{ color: #6ee7a8; }}
                                         .bad {{ color: #ff938a; }} }}
  table {{ border-collapse: collapse; }}
  td {{ padding: 0.2rem 1.2rem 0.2rem 0; vertical-align: top; }}
</style></head><body>{body}</body></html>"""
    )


@app.get("/healthz")
def healthz():
    """Liveness, and whether the dashboard has data to serve.

    A platform health check that only proves the process is up will report
    green while the page renders empty, so this looks for the file too.
    """
    data = PUBLIC / "data.json"
    return {
        "status": "ok",
        "data": data.exists(),
        "data_bytes": data.stat().st_size if data.exists() else 0,
    }


@app.get("/signin", response_class=HTMLResponse)
def signin():
    """Say who you are. One field, no password, and the page says as much.

    Its own page rather than a panel on the workbench, because a form sitting
    above the thing it controls reads as decoration and gets skipped. This one
    has to be passed through.
    """
    page_file = PUBLIC / "signin.html"
    if not page_file.is_file():
        raise HTTPException(status_code=404, detail="signin.html is not deployed")
    return FileResponse(page_file, headers={"Cache-Control": "no-store"})


@app.get("/workbench", response_class=HTMLResponse)
def workbench(mibel_session: str | None = Cookie(default=None)):
    """Where a person asks the agent for something and it acts.

    A separate page from the dashboard because the two have different
    requirements: the dashboard reads a committed file and always works, this
    one needs a database and a model endpoint.

    The session is checked here, on the server, before the file is sent. Letting
    the page load and having its own script discover there is no session would
    show the visitor a working interface for a moment and then take it away,
    which looks like a fault rather than a redirect.
    """
    from iberian.app.session import SESSIONS, verify

    # Both checks, and the second is the one that matters. A signature only
    # proves this server issued the cookie at some point; the store is what
    # knows whether the session behind it is still alive. Serving the page on
    # the signature alone would show a working interface to somebody who has
    # signed out or whose hour is up, and then take it away once the first
    # request came back empty.
    found = verify(mibel_session)
    if found is None or SESSIONS.get(found[1]) is None:
        return RedirectResponse("/signin", status_code=303)

    page_file = PUBLIC / "workbench.html"
    if not page_file.is_file():
        raise HTTPException(status_code=404, detail="workbench.html is not deployed")
    # no-store, not no-cache: a back button that serves this page from the
    # browser's cache after signing out shows somebody else's name in the
    # corner, and re-fetching it costs nothing.
    return FileResponse(page_file, headers={"Cache-Control": "no-store"})


@app.get("/", response_class=HTMLResponse)
def dashboard():
    """The page all three target users get, with no sign in.

    No cache header: the file is small and is replaced whenever the export
    runs, and a stale dashboard that says nothing about its own staleness is
    worse than a second of load time.
    """
    page_file = PUBLIC / "index.html"
    if not page_file.exists():
        raise HTTPException(500, "app/public/index.html is missing from the build")
    return FileResponse(
        page_file, media_type="text/html; charset=utf-8",
        headers={"Cache-Control": "no-cache"},
    )


@app.get("/data.json")
def data_json():
    if not (PUBLIC / "data.json").exists():
        raise HTTPException(
            503,
            "No published data. Run scripts/export_public_data.py before deploying.",
        )
    return FileResponse(
        PUBLIC / "data.json", media_type="application/json",
        headers={"Cache-Control": "no-cache"},
    )


@app.get("/auth", response_class=HTMLResponse)
def auth_status():
    missing = configured()
    if missing:
        rows = "".join(f"<li><code>{html.escape(m)}</code></li>" for m in missing)
        return page(
            "MIBEL Market Intelligence",
            "<h1>MIBEL Market Intelligence</h1>"
            '<p class="bad">Not configured. Missing environment variables:</p>'
            f"<ul>{rows}</ul>",
        )
    return page(
        "MIBEL Market Intelligence",
        "<h1>MIBEL Market Intelligence</h1>"
        "<p>Detects price decoupling between Portugal and Spain in the MIBEL "
        "day ahead market.</p>"
        f"<p>Workspace: <code>{html.escape(HOST)}</code><br>"
        f"Scopes requested: <code>{html.escape(SCOPES)}</code></p>"
        '<p><a href="/login">Sign in with Databricks</a></p>'
        "<p><small>Sign in requires an account in that workspace.</small></p>",
    )


@app.get("/login")
def login():
    missing = configured()
    if missing:
        raise HTTPException(500, f"Not configured: {', '.join(missing)}")

    _prune()
    state = secrets.token_urlsafe(24)
    verifier, challenge = _pkce()
    _PENDING[state] = {"verifier": verifier, "created": time.time()}

    query = urllib.parse.urlencode(
        {
            "client_id": CLIENT_ID,
            "response_type": "code",
            "redirect_uri": REDIRECT_URI,
            "scope": SCOPES,
            "state": state,
            "code_challenge": challenge,
            "code_challenge_method": "S256",
        }
    )
    return RedirectResponse(f"{AUTHORIZE_URL}?{query}", status_code=302)


@app.get("/callback", response_class=HTMLResponse)
def callback(
    code: str | None = Query(default=None),
    state: str | None = Query(default=None),
    error: str | None = Query(default=None),
    error_description: str | None = Query(default=None),
):
    if error:
        return page(
            "Sign in failed",
            '<h1 class="bad">Databricks refused the request</h1>'
            f"<pre>{html.escape(error)}\n"
            f"{html.escape(error_description or '')}</pre>"
            '<p><a href="/auth">Back</a></p>',
        )

    if not code or not state:
        return page(
            "Sign in failed",
            '<h1 class="bad">No code returned</h1>'
            '<p><a href="/auth">Back</a></p>',
        )

    pending = _PENDING.pop(state, None)
    if pending is None:
        # Either the state was forged, or the flow was started before the
        # instance restarted. Render's free tier spins down, which makes the
        # second case ordinary rather than suspicious.
        return page(
            "Sign in failed",
            '<h1 class="bad">Unknown state</h1>'
            "<p>The sign in did not start on this instance, or it expired. "
            'Free instances spin down when idle.</p><p><a href="/login">'
            "Try again</a></p>",
        )

    try:
        response = requests.post(
            TOKEN_URL,
            auth=(CLIENT_ID, CLIENT_SECRET),
            data={
                "grant_type": "authorization_code",
                "code": code,
                "redirect_uri": REDIRECT_URI,
                "code_verifier": pending["verifier"],
            },
            timeout=30,
        )
        body = response.json()
    except Exception as exc:
        return page(
            "Sign in failed",
            '<h1 class="bad">Could not reach the token endpoint</h1>'
            f"<pre>{html.escape(str(exc)[:400])}</pre>",
        )

    if "access_token" not in body:
        return page(
            "Sign in failed",
            '<h1 class="bad">Token exchange rejected</h1>'
            f"<pre>{html.escape(json.dumps(body, indent=2)[:1200])}</pre>"
            "<p>The redirect URI must match a registered one exactly, "
            "including the scheme and any trailing slash.</p>",
        )

    from iberian.app.session import SESSIONS, sign

    claims = decode_claims(body["access_token"])
    email = claims.get("sub") or ""
    if not email:
        return page(
            "Sign in failed",
            '<h1 class="bad">The token names nobody</h1>'
            "<p>The exchange succeeded but the token carries no subject, so "
            "there is no identity to attribute work to.</p>"
            '<p><a href="/signin">Back</a></p>',
        )

    # The one use this application makes of the platform token. It carries the
    # person's whole workspace, so it is spent here and not kept: what is stored
    # is the Lakebase credential it produces, which opens a database connection
    # as that person and does nothing else.
    try:
        credential = database_credential_for(body["access_token"])
    except Exception as exc:
        return page(
            "Signed in, but the database refused",
            '<h1 class="bad">Databricks knows you, Lakebase does not</h1>'
            f"<p>Signed in as <code>{html.escape(email)}</code>, but generating "
            "a database credential failed.</p>"
            f"<pre>{html.escape(str(exc)[:600])}</pre>"
            "<p>The usual cause is that this identity has no Postgres role in "
            "the project yet. A role is a database object and workspace "
            "permissions do not create one.</p>"
            '<p><a href="/signin">Back</a></p>',
        )
    finally:
        # Belt and braces. The local name is the only reference this function
        # holds, and it goes out of scope anyway, but saying so here is how the
        # next person reading this knows it was a decision.
        body.pop("access_token", None)
        body.pop("refresh_token", None)

    session_id = SESSIONS.open(email=email, database_credential=credential)

    response = RedirectResponse("/workbench", status_code=303)
    response.set_cookie(
        "mibel_session",
        sign(email, session_id),
        max_age=SESSION_COOKIE_SECONDS,
        httponly=True,
        samesite="lax",
    )
    return response