"""Label episodes one at a time, in the terminal, without opening a spreadsheet.

The evaluation set is the ground truth the agent is scored against, so the
labels have to be a person's judgement rather than generated output. If they
were generated by the same system under test, the metric would measure the
system agreeing with itself.

What can be removed is the friction. This prints one episode at a time with
the evidence laid out, offers the vocabulary as a numbered menu, and saves
after every answer so an interruption costs nothing.

    python scripts/label_episodes.py
    python scripts/label_episodes.py --limit 5     # a short sitting
    python scripts/label_episodes.py --by-spread   # largest first instead
    python scripts/label_episodes.py --all         # revisit ones already done

Type the number, or `s` to skip, or `q` to stop.

Episodes are offered for variety rather than by size. Sorting by spread puts
eleven near identical August days at the front, and a sample of eleven near
identical days would overstate the agent's accuracy: it would only have had to
get one situation right. Interleaving the strata means that stopping halfway
still leaves a representative set.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd

CAUSES = [
    ("saturation_planned", "Border at its limit, explained by a planned outage"),
    ("saturation_unplanned", "Border at its limit, explained by an unplanned outage"),
    ("saturation_no_notice", "Border at its limit, no notice accounts for it"),
    ("not_saturated", "Priced apart with headroom on the border"),
    ("threshold_artifact", "Spread at the rounding epsilon, not a real event"),
    ("unclear", "The available evidence does not settle it"),
]


def interleave(frame: pd.DataFrame) -> list:
    """Round robin across strata, so the first few episodes are not all alike.

    A stratum is the combination the evidence puts an episode in: the cause the
    rules propose, the asset under notice, and whether that notice was planned.
    Taking one from each in turn means the first sitting covers the range of
    situations rather than eleven consecutive August days with the same asset
    under the same planned outage.
    """
    if frame.empty:
        return []

    work = frame.copy()
    work["_spread"] = pd.to_numeric(work["peak_abs_spread"], errors="coerce").fillna(0)
    work["_stratum"] = (
        work["candidate_cause"].astype(str)
        + "|"
        + work["tightest_asset"].astype(str)
        + "|"
        + work["tightest_status"].astype(str)
    )
    work = work.sort_values("_spread", ascending=False)
    # Position within its own stratum, so rank 0 of every stratum comes first.
    work["_rank"] = work.groupby("_stratum").cumcount()
    work = work.sort_values(["_rank", "_spread"], ascending=[True, False])
    return list(work.index)


def show(row: pd.Series, position: int, total: int, candidate: bool = False) -> None:
    print("\n" + "=" * 70)
    print(f"[{position}/{total}]  {row['episode_key']}   market day {row['market_day']}")
    print("=" * 70)

    print(f"\n  Started       {row['start_utc']}")
    print(f"  Duration      {row['duration_hours']} h over {row['intervals']} intervals")
    print(f"  Peak spread   {row['peak_spread']} EUR/MWh, {row['premium_side']} pays")
    print(f"  Severity      {row['severity']}")
    if pd.notna(row.get("extra_cost_eur")):
        print(f"  Extra cost    {float(row['extra_cost_eur']):,.0f} EUR")

    print("\n  Border")
    print(f"    Saturated in  {row['share_saturated']} of the episode's intervals")
    print(f"    Mean use      {row['mean_utilisation']}")
    print(f"    Min capacity  {row['min_capacity_mw']} MW")

    print("\n  Notices available before it began")
    if int(row["notices"]) == 0:
        print("    None. No transmission notice covers this interval in this direction.")
    else:
        print(f"    {int(row['notices'])} notice(s). Tightest:")
        print(f"      {row['tightest_asset']}  {row['tightest_available_mw']} MW  "
              f"{row['tightest_status']}, published {row['tightest_published']}")
        gap = row.get("unexplained_mw")
        if pd.notna(gap):
            gap = float(gap)
            if gap > 0:
                print(f"    Unexplained   {gap:,.0f} MW")
                print("      The notice allows MORE capacity than the border actually")
                print("      had, so it does not account for the collapse. Look twice.")
            else:
                print(f"    Notice is {abs(gap):,.0f} MW tighter than the border figure,")
                print("      which is normal: one asset among several parallel paths.")

    # The rules' own answer is deliberately NOT shown before the question.
    #
    # It used to be, one line above the menu, and the first pass through this
    # sheet agreed with it on every single episode. That is what anchoring
    # does, and it is not a failure of attention: a proposed answer next to a
    # menu reads as the answer, especially on the fortieth episode of a
    # sitting. The result was a ground truth that was the system's own output
    # wearing a different column name, which would have made the accuracy
    # figure measure the system agreeing with itself.
    #
    # It is printed after the answer instead, where it is feedback rather than
    # a suggestion, and `--show-candidate` puts it back for anyone who wants to
    # review the rules rather than the episodes.
    if candidate:
        print(f"\n  The rules would say: {row['candidate_cause']}")


def ask(row: pd.Series) -> tuple[str, str, str] | None:
    print("\n  " + "  ".join(f"[{i}] {name}" for i, (name, _) in enumerate(CAUSES, 1)))
    for index, (name, description) in enumerate(CAUSES, 1):
        print(f"    {index}. {name:<24} {description}")
    print("    s. skip    q. stop and save")

    while True:
        answer = input("\n  cause > ").strip().lower()
        if answer in {"q", "quit"}:
            return None
        if answer in {"s", "skip", ""}:
            return ("", "", "")
        if answer.isdigit() and 1 <= int(answer) <= len(CAUSES):
            cause = CAUSES[int(answer) - 1][0]
            break
        print("  Type a number, or s to skip, or q to stop.")

    confidence = ""
    while confidence not in {"high", "medium", "low"}:
        confidence = input("  confidence (high/medium/low) > ").strip().lower() or "medium"
        if confidence not in {"high", "medium", "low"}:
            print("  high, medium or low.")

    notes = input("  notes (optional) > ").strip()
    if cause != row["candidate_cause"] and not notes:
        print("\n  You disagreed with the rules. That is the most useful row in the")
        print("  sheet, and it is worth a sentence saying why.")
        notes = input("  notes > ").strip()

    return (cause, confidence, notes)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--path", default="evaluation/episodes.csv")
    parser.add_argument("--all", action="store_true", help="include already labelled")
    parser.add_argument("--limit", type=int, help="stop after this many")
    parser.add_argument(
        "--show-candidate",
        action="store_true",
        help="show the rules' answer before asking. Off by default: it anchors",
    )
    parser.add_argument(
        "--by-spread",
        action="store_true",
        help="largest spread first, rather than interleaving the strata",
    )
    args = parser.parse_args()

    path = Path(args.path)
    if not path.exists():
        raise SystemExit(f"{path} not found. Run scripts/build_evaluation_set.py first.")

    sheet = pd.read_csv(path, dtype=str, keep_default_na=False)
    for column in ("true_cause", "confidence", "notes"):
        if column not in sheet.columns:
            sheet[column] = ""

    pending = sheet if args.all else sheet[sheet["true_cause"].str.strip() == ""]
    indices = list(pending.index if args.by_spread else interleave(pending))
    if args.limit:
        indices = indices[: args.limit]

    if not indices:
        print("Everything is labelled. Use --all to revisit.")
        return 0

    order = "largest spread first" if args.by_spread else "interleaved for variety"
    print(f"{len(indices)} episode(s) to label, {order}.")

    done = 0
    for position, index in enumerate(indices, 1):
        show(sheet.loc[index], position, len(indices), candidate=args.show_candidate)
        answer = ask(sheet.loc[index])
        if answer is None:
            break
        cause, confidence, notes = answer
        if not cause:
            continue

        # After the answer, never before. Seeing where you differ from the
        # rules is the useful part; seeing it first is the anchoring.
        candidate = str(sheet.loc[index, "candidate_cause"])
        if cause == candidate:
            print(f"  (the rules agreed: {candidate})")
        else:
            print(f"  (the rules would have said {candidate}. Yours is the label.)")

        sheet.loc[index, "true_cause"] = cause
        sheet.loc[index, "confidence"] = confidence
        sheet.loc[index, "notes"] = notes
        # Written after every answer, so stopping halfway costs nothing.
        sheet.to_csv(path, index=False)
        done += 1

    labelled = int((sheet["true_cause"].str.strip() != "").sum())
    print(f"\n  {done} labelled this session. {labelled} of {len(sheet)} in total.")

    if labelled:
        agreed = int(
            (
                (sheet["true_cause"].str.strip() != "")
                & (sheet["true_cause"] == sheet["candidate_cause"])
            ).sum()
        )
        print(f"  You agreed with the rules on {agreed} of {labelled}.")
        if agreed < labelled:
            print("  The disagreements are where the agent has to earn its place.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())